[tool.poetry]
name = "math_tools"
version = "0.1.0"
description = "A package for math utilitlies"
authors = ["Yang Wu"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
numpy = ">=1.22.3"
sympy = ">=1.10.1"
scipy = ">=1.8.1"
scikit-learn = ">=1.1.1"
matplotlib = ">=3.5.2"

[tool.poetry.dev-dependencies]
pytest = ">=7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
