[tool.poetry]
name = "math_tools"
version = "0.1.0"
description = "A package for math utilitlies"
authors = ["Yang Wu"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
